language: ruby
rvm:
- 2.1
branches:
  only:
  - master
addons:
  ssh_known_hosts: squeak.org
install:
- gem install jekyll jekyll-sitemap
before_script:
- openssl aes-256-cbc -K $encrypted_7202fd93a95a_key -iv $encrypted_7202fd93a95a_iv
  -in .deploy.enc -out ~/.ssh/deploy -d
- chmod 600 ~/.ssh/deploy
- eval `ssh-agent -s`
- ssh-add -D
- ssh-add ~/.ssh/deploy
script:
- jekyll build
after_success:
- rsync -crvz --delete _site/ $encrypted_host:$encrypted_path
