language: ruby
sudo: false
rvm:
- 2.1
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - squeak.de
  - 87.106.17.169
install:
- gem install jekyll jekyll-sitemap jekyll-redirect-from
before_script:
- chmod 600 ~/.ssh/deploy
- eval `ssh-agent -s`
- ssh-add -D
- ssh-add ~/.ssh/deploy
script:
- jekyll build
after_success:
- mv _site ../
- git checkout --orphan gh-pages
- git rm -rfq .
- mv ../_site/* .
- git remote set-url origin git@github.com:squeak-smalltalk/squeak.de.git
- git config --global user.name "Fabio Niephaus"
- git config --global user.email "fniephaus@users.noreply.github.com"
- git config --global push.default matching
- git add .
- git commit -am "Travis CI autocommit from travis build ${TRAVIS_BUILD_NUMBER}"
- git push -fq origin gh-pages:gh-pages
before_install:
- openssl aes-256-cbc -K $encrypted_2808a4333421_key -iv $encrypted_2808a4333421_iv
  -in .deploy.enc -out ~/.ssh/deploy -d
