language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.3
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
- bundle update
- if [[ "${TRAVIS_BRANCH}" == "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
    openssl aes-256-cbc -K $encrypted_7202fd93a95a_key -iv $encrypted_7202fd93a95a_iv
      -in .deploy.enc -out ~/.ssh/deploy -d;
    chmod 600 ~/.ssh/deploy;
  fi
script: "bundle exec rake test"
after_success:
- if [[ "${TRAVIS_BRANCH}" == "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
    ssh-keyscan -t ecdsa-sha2-nistp256 -p $encrypted_proxy_port -H $encrypted_proxy_host 2>&1 | tee -a $HOME/.ssh/known_hosts > /dev/null;
    echo "$encrypted_host ecdsa-sha2-nistp256 $encrypted_public_key" | tee -a $HOME/.ssh/known_hosts > /dev/null;
    rsync -crvz -e "ssh -o ProxyCommand='ssh -l $encrypted_proxy_user -i $HOME/.ssh/deploy -p $encrypted_proxy_port -W %h:%p $encrypted_proxy_host' -l $encrypted_user -i $HOME/.ssh/deploy" --delete _site/ $encrypted_host:$encrypted_path;
  fi
