language: ruby
cache: bundler
sudo: false
rvm:
- 2.1
branches:
  only:
  - master
addons:
  ssh_known_hosts: squeak.org
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
- bundle update
- openssl aes-256-cbc -K $encrypted_7202fd93a95a_key -iv $encrypted_7202fd93a95a_iv
  -in .deploy.enc -out ~/.ssh/deploy -d
- chmod 600 ~/.ssh/deploy
script: "bundle exec rake test"
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    rsync -crvz -e "ssh -i $HOME/.ssh/deploy" --delete _site/ $encrypted_host:$encrypted_path;
  fi
