# Site settings
title: Squeak/Smalltalk
copyright: Squeak Projekt

# SEO
description: >
  Squeak is a modern, open source, full-featured implementation of the powerful
  Smalltalk programming language and environment.
author: Squeak Foundation

collections:
  # Order matters
  events:
    title: Events
    sort_by: order
  downloads:
    title: Downloads
    sort_by: order
  community:
    title: Community
    sort_by: order
  projects:
    title: Projekte
    sort_by: title
  documentation:
    title: Dokumentation
    sort_by: order
    visible-sm: <i class="fa fa-book"></i>
    mobile-title: Docs

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      cols: 6
      href-external: true
  -
    scope:
      path: ""
      type: "research"
    values:
      cols: 12

# Enable SASS support
sass:
  sass_dir: _sass
  style: :compressed

# Serving
host: 0.0.0.0

# Caching
build_version: 1.1
staticurl: static/

# Build settings
highlighter: pygments
markdown: kramdown

# Enable plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

include: [_pages]

# Exclude vendor dir which Travis uses to bundle all gems on its build servers
exclude: [vendor, README.md]
