# Site settings
title: Squeak Smalltalk
welcome: >
  Squeak is an open-source Smalltalk programming system with fast execution
  environments for all major platforms. It features the Morphic framework,
  which promotes low effort graphical, interactive application development and
  maintenance. Many projects have been successfully created with Squeak. They
  cover a wide range of domains such as education, multimedia, gaming, research,
  and commerce.
baseurl: "/squeak.org"
url: ""

# Build settings
markdown: kramdown

collections:
  features:
    title: Features
  community:
    title: Community
  projects:
    title: Projects
  documentation:
    title: Documentation
  downloads:
    title: Downloads
  development:
    title: Development
