# Site settings
title: Squeak Smalltalk

# SEO
description:
  Squeak is a modern, open source, full-featured implementation of the powerful
  Smalltalk programming language and environment.
author: Squeak Foundation

collections:
  # Order matters
  features:
  community:
  projects:
  documentation:
  downloads:
  development:

defaults:
  - scope:
      path: ""
    values:
      img-border: true

# Paths
baseurl: "/squeak.org"
url: ""

# Build settings
highlighter: pygments
markdown: kramdown

# Enable plugins
gems:
  - jekyll-sitemap