# Site settings
title: Squeak Smalltalk
copyright: Squeak Project

# SEO
description: >
  Squeak is a modern, open source, full-featured implementation of the powerful
  Smalltalk programming language and environment.
author: Squeak Foundation

collections:
  # Order matters
  features:
    title: Features
  community:
    title: Community
  projects:
    title: Projects
  documentation:
    title: Documentation
    visible-sm: Docs
    mobile-title: Docs
  downloads:
    title: Downloads
  development:
    title: Development
    visible-sm: Dev
  license:
    title: License
    hidden: true
  board:
    title: Squeak Oversight Board
    hidden: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      cols: 6
      href-external: true

# Paths
baseurl: "/squeak.org"
url: ""

# Serving
host:    0.0.0.0

# Build settings
highlighter: pygments
markdown: kramdown

# Enable plugins
gems:
  - jekyll-sitemap