# Site settings
title: Squeak Smalltalk

# SEO
description:
  Squeak is a modern, open source, full-featured implementation of the powerful
  Smalltalk programming language and environment.
author: Squeak Foundation

collections:
  # Order matters
  features:
    title: Features
  community:
    title: Community
  projects:
    title: Projects
  documentation:
    title: Documentation
    mobile-title: Docs
  downloads:
    title: Downloads
  development:
    title: Development

defaults:
  - scope:
      path: ""
    values:
      img-border: true

# Paths
baseurl: "/squeak.org"
url: ""

# Serving
host:    0.0.0.0

# Build settings
highlighter: pygments
markdown: kramdown

# Enable plugins
gems:
  - jekyll-sitemap