# Site settings
title: Squeak Smalltalk

# SEO
description:
  Squeak is a modern, open source, full-featured implementation of the powerful
  Smalltalk programming language and environment.
author: Squeak Foundation

collections:
  # Output all pages
  pages:
    output: true # Hide on navigation and front page
  # Order matters
  features:
  community:
  projects:
  documentation:
  downloads:
  development:

# Paths
baseurl: "/squeak.org"
url: ""

# Build settings
markdown: kramdown