# Site settings
title: Squeak/Smalltalk
copyright: Squeak Projekt

# SEO
description: >
  Squeak is a modern, open source, full-featured implementation of the powerful
  Smalltalk programming language and environment.
author: Squeak Foundation

collections:
  # Order matters
  about:
    title: Über
    sort_by: order
  downloads:
    title: Herunterladen
    sort_by: order
  news:
    title: Neuigkeiten
    sort_by: order
  documentation:
    title: Dokumentation
    sort_by: order
  education:
    title: Bildung und Lehre
    sort_by: order

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      cols: 6
      href-external: true

# Enable SASS support
sass:
  sass_dir: _sass
  style: :compressed

# Serving
host: 0.0.0.0

# Caching
build_version: 1.1
staticurl: static/

# Build settings
highlighter: pygments
markdown: kramdown

# Enable plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

include: [_pages]

# Exclude vendor dir which Travis uses to bundle all gems on its build servers
exclude: [vendor, README.md]
