# Site settings
title: Squeak/Smalltalk
copyright: Squeak Project

# SEO
description: >
  Squeak is a modern, open source, full-featured implementation of the powerful
  Smalltalk programming language and environment.
author: Squeak Foundation

collections:
  # Order matters
  features:
    title: Features
    sort_by: order
  downloads:
    title: Downloads
    sort_by: order
  community:
    title: Community
    sort_by: order
  projects:
    title: Projects
    sort_by: title
  documentation:
    title: Documentation
    sort_by: order
    visible-sm: <i class="fa fa-book"></i>
    mobile-title: Docs
  development:
    title: Development
    sort_by: order
    visible-sm: <i class="fa fa-code"></i>
  research:
    title: Research
    visible-sm: <i class="fa fa-flask"></i>
    sort_by: order
  board:
    title: Squeak Oversight Board
    sort_by: order
    hidden: true
  license:
    title: License
    sort_by: order
    hidden: true
  imprint:
    title: Imprint
    sort_by: order
    hidden: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      cols: 6
      href-external: true
  -
    scope:
      path: ""
      type: "research"
    values:
      cols: 12

# Paths
baseurl: ""
url: ""

# Enable SASS support
sass:
  sass_dir: _sass
  style: :compressed

# Serving
host: 0.0.0.0

# Caching
build_version: 0.5
staticurl: "static/"

# Build settings
highlighter: pygments
markdown: kramdown

# Enable plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll/scholar


include: [_misc]

# Exclude vendor dir which Travis uses to bundle all gems on its build servers
exclude: [vendor, README.md, _research/references.bib]

# jekyll-scholar
scholar:
  sort_by: none
  order: ascending

  source: ./_research
  bibliography: references.bib
  bibliography_template: "{{reference}}"
  bibliography_template: bib
  bibtex_options:
    parse_names: false
