# Site settings
title: Squeak Smalltalk
copyright: Squeak Project

# SEO
description: >
  Squeak is a modern, open source, full-featured implementation of the powerful
  Smalltalk programming language and environment.
author: Squeak Foundation

collections:
  # Order matters
  features:
    title: Features
    sort_by: order
  community:
    title: Community
    sort_by: order
  projects:
    title: Projects
    sort_by: title
  documentation:
    title: Documentation
    sort_by: order
    visible-sm: Docs
    mobile-title: Docs
  downloads:
    title: Downloads
    sort_by: order
  development:
    title: Development
    sort_by: order
    visible-sm: Dev
  license:
    title: License
    sort_by: order
    hidden: true
  board:
    title: Squeak Oversight Board
    sort_by: order
    hidden: true
  imprint:
    title: Imprint
    sort_by: order
    hidden: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      cols: 6
      href-external: true

# Paths
baseurl: ""
url: ""

# Serving
host:    0.0.0.0

# Caching
build_version: 0.0.1
staticurl: "static/"

# Build settings
highlighter: pygments
markdown: kramdown

# Enable plugins
gems:
  - jekyll-sitemap